export const projects = [
  {
    id: '1',
    screenshot: '/bidzy.png',
    title: 'Bidzy',
    subTitle: 'Live bidding logistics platform',
    stack: [/* update manually */],
    description: `Bidzy is a logistics bidding platform that helps users get services at lower prices by letting delivery partners compete in real time. With live bidding, order tracking, and a smart dashboard, Bidzy transforms how logistics and pricing work.`,
    date: 'Dec 5, 2024',
    github: 'https://github.com/Tez2213/Bidzy',
    live: 'https://bidzy.vercel.app/',
    color: 'rgba(249,115,22)',
    btnBg: 'rgba(154,52,18,0.5)',
    btnBgHover: 'rgba(67,20,7)',
    cardBg: 'rgba(154,52,18,0.05)',
  },
  {
    id: '2',
    screenshot: '/portxfolio.png',
    title: 'PortxFolio',
    subTitle: 'Hackathon for developers and founders',
    stack: [/* update manually */],
    description: `PortxFolio was a 2-week hackathon built to connect innovative student minds. We designed, hosted, and managed the event—featuring 90+ participants and startup-ready projects. A celebration of creativity, code, and collaboration.`,
    date: 'Mar 12, 2025',
    github: '',
    live: 'https://portxfolio25.devpost.com/',
    color: 'rgba(79,70,229)',
    btnBg: 'rgba(55,48,163,0.5)',
    btnBgHover: 'rgba(30,27,75)',
    cardBg: 'rgba(55,48,163,0.05)',
  },
  {
    id: '3',
    screenshot: '/bintrack.png',
    title: 'BinTrack',
    subTitle: 'Waste tracking & sustainability platform',
    stack: [/* update manually */],
    description: `BinTrack is a sustainability-driven tool that helps users track and manage their waste footprint. Built with a microfrontend architecture, it offers flexibility, modularity, and a clean dashboard for actionable insights.`,
    date: 'Nov 19, 2024',
    github: 'https://github.com/Tez2213/bin-tracker',
    live: 'https://bin-tracker-delta.vercel.app',
    color: 'rgba(139,92,246)',
    btnBg: 'rgba(91,33,182,0.5)',
    btnBgHover: 'rgba(46,16,101)',
    cardBg: 'rgba(91,33,182,0.05)',
  },
  {
    id: '4',
    screenshot: '/scaleonn.png',
    title: 'Scaleon',
    subTitle: 'Agency website for local businesses',
    stack: [/* update manually */],
    description: `Scaleon is a website-making agency focused on helping small businesses grow with clean, modern, and budget-friendly websites. Built with performance and design in mind, Scaleon delivers digital presence that works.`,
    date: 'Jan 2, 2024',
    github: '',
    live: 'https://scaleonn.com',
    color: 'rgba(34,197,94)',
    btnBg: 'rgba(22,101,52,0.5)',
    btnBgHover: 'rgba(5,46,22)',
    cardBg: 'rgba(22,101,52,0.05)',
  },
];
