export const projects = [
  {
    id: '1',
    screenshot: '/dev-overflow.png',
    title: 'Bidzy',
    subTitle: 'Logistic and delivery platform',
    stack: [
      'next.js',
      'typescript',
      'clerck',
      'tailwindcss',
      'mongodb',
      'mongoose',
      'clerck webhooks',
    ],
    description: `Bidzy is a modern logistics and delivery platform designed to streamline the shipping process for businesses and consumers alike. Built with Next.js, TypeScript, and Tailwind CSS, it offers a seamless user experience with features like real-time tracking, order management, and automated notifications. The platform includes a robust API for integration with third-party services and a user-friendly dashboard for managing shipments. Authentication and authorization are powered by Clerk, ensuring secure and personalized user interactions.`,
    date: 'Dec 5, 2024',
    github: 'https://github.com/Tez2213/Bidzy',
    live: 'https://bidzy.vercel.app/',
    color: 'rgba(249,115,22)',
    btnBg: 'rgba(154,52,18,0.5)',
    btnBgHover: 'rgba(67,20,7)',
    cardBg: 'rgba(154,52,18,0.05)',
  },
  {
    id: '2',
    screenshot: '/meta-market.png',
    title: 'BinTrack',
    subTitle: 'NFT marketplace UI website',
    stack: [
      'react',
      'typescript',
      'tailwindcss',
      'nx',
      'rollup',
      'Module Federation',
      'vitest',
      'playwright',
      'storybook',
      'svgr',
      'lint-staged',
      'husky',
      'ci/cd',
      'aws',
    ],
    description:
      'Meta Market is a NFT marketplace built using a monorepo architecture, leveraging React and microfrontend design principles. The application is divided into five independent React applications, each serving a distinct function within the ecosystem, along with shared design system and icons packages. This microfrontend architecture ensures modularity, scalability, and independent deployment, while the monorepo setup allows for seamless code sharing and consistency across all projects.',
    date: 'Nov 19, 2024',
    github: 'https://github.com/Tez2213/bin-tracker',
    live: 'https://bin-tracker-delta.vercel.app',
    color: 'rgba(139,92,246)',
    btnBg: 'rgba(91,33,182,0.5)',
    btnBgHover: 'rgba(46,16,101)',
    cardBg: 'rgba(91,33,182,0.05)',
  },
  {
    id: '3',
    screenshot: '/room-manager.png',
    title: 'Rewear',
    subTitle: 'Room management and reservations app',
    stack: [
      'react',
      'typescript',
      'tanstack',
      'styled component',
      'node',
      "api's",
      'express',
      'mongodb',
      'mongoose',
      'JWT',
      'cloudinary',
    ],
    description:
      'Room Manager is a comprehensive room management and reservation platform designed to streamline operations for administrators and guests alike. The application allows users to browse available rooms, register visitors and guests, and manage multiple admin accounts with role-based permissions. Authentication and authorization were custom-built using JSON Web Tokens (JWT) for a secure and tailored experience. Cloudinary powers image upload and optimization, ensuring fast and high-quality visuals.',
    date: 'Sep 2, 2024',
    github: 'https://github.com/Tez2213/ReWear',
     live: 'https://portxfolio25.devpost.com/',
    color: 'rgba(79,70,229)',
    btnBg: 'rgba(55,48,163,0.5)',
    btnBgHover: 'rgba(30,27,75)',
    cardBg: 'rgba(55,48,163,0.05)',
  },
  {
    id: '4',
    screenshot: '/fintechracy.png',
    title: 'scaleonn',
    subTitle: 'scaleonn official website',
    stack: ['react', 'tailwindcss', 'framer motion', 'shadcn'],
    description: `Fintechracy is on a mission to eliminate paper receipts by providing innovative software solutions. After two unsuccessful attempts to develop a professional website, I stepped in to deliver a final version that met the company's vision and market standards. The website, built with React, Tailwind CSS, ShadCN, and Framer Motion, features smooth animations, complete responsiveness, and multi-language support for a seamless global user experience.`,
    date: 'Jan 2, 2024',
    github: '',
    live: 'http://scaleonn.com',
    color: 'rgba(34,197,94)',
    btnBg: 'rgba(22,101,52,0.5)',
    btnBgHover: 'rgba(5,46,22)',
    cardBg: 'rgba(22,101,52,0.05)',
  },
  
];
